import base64
from io import BytesIO

import qrcode
import streamlit as st
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes


# ---------- AES HELPERS ----------

def encrypt_file(file_bytes: bytes):
    """
    Encrypts file_bytes using AES-256-GCM.
    Returns (encrypted_bytes, key_bytes).
    Layout: nonce (16) | tag (16) | ciphertext
    """
    key = get_random_bytes(32)  # 256-bit key
    cipher = AES.new(key, AES.MODE_GCM)
    ciphertext, tag = cipher.encrypt_and_digest(file_bytes)

    encrypted = cipher.nonce + tag + ciphertext
    return encrypted, key


def decrypt_file(encrypted_bytes: bytes, key_bytes: bytes):
    """
    Decrypts encrypted_bytes produced by encrypt_file().
    Expected layout: nonce | tag | ciphertext
    """
    if len(encrypted_bytes) < 32:
        raise ValueError("Encrypted data is too short or corrupted.")

    nonce = encrypted_bytes[:16]
    tag = encrypted_bytes[16:32]
    ciphertext = encrypted_bytes[32:]

    cipher = AES.new(key_bytes, AES.MODE_GCM, nonce=nonce)
    decrypted = cipher.decrypt_and_verify(ciphertext, tag)
    return decrypted


# ---------- QR HELPERS ----------

def generate_qr_image(data_str: str):
    qr = qrcode.QRCode(
        version=1,
        box_size=8,
        border=4,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
    )
    qr.add_data(data_str)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    # >>> FIX: if it's a qrcode.image.pil.PilImage, extract the actual PIL object
    if hasattr(img, "get_image"):
        img = img.get_image()

    return img



def pil_image_to_bytes(img):
    buf = BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf.getvalue()


# ---------- STREAMLIT UI ----------

st.set_page_config(page_title="Secure File Sharing with QR Key Exchange")
st.title("🔐 Secure File Sharing with QR-based Key Exchange")

st.write(
    """
This prototype demonstrates **AES-256 encryption** of files and **QR-based offline key sharing**.

**Workflow:**
1. Encrypt a file → AES key generated.
2. Key is converted to **Base64** and **QR code**.
3. Share encrypted file normally (Drive, WhatsApp, email).
4. Share key ONLY via QR to prevent digital leakage.
5. Receiver uploads encrypted file + key → decrypts original file.
"""
)

tab_encrypt, tab_decrypt = st.tabs(["🔒 Encrypt File", "🔓 Decrypt File"])


# ---------- ENCRYPT TAB ----------

with tab_encrypt:
    st.subheader("Upload file to encrypt")

    enc_file = st.file_uploader(
        "Choose any file (PDF, DOCX, image, etc.)", key="enc_file"
    )

    if enc_file:
        file_bytes = enc_file.read()
        st.info(f"Selected: **{enc_file.name}** ({len(file_bytes)} bytes)")

        if st.button("Encrypt File"):
            try:
                encrypted_bytes, key_bytes = encrypt_file(file_bytes)

                key_b64 = base64.b64encode(key_bytes).decode("utf-8")
                st.success("✅ Encrypted successfully!")

                st.markdown("### 🔑 AES Key (Base64)")
                st.code(key_b64)

                qr_img = generate_qr_image(key_b64)
                qr_bytes = pil_image_to_bytes(qr_img)

                st.markdown("### 📷 QR Code for the Key")
                st.image(qr_img, caption="Scan to retrieve AES key")

                enc_filename = enc_file.name + ".enc"

                st.download_button(
                    "⬇️ Download Encrypted File",
                    data=encrypted_bytes,
                    file_name=enc_filename,
                    mime="application/octet-stream",
                )

                st.download_button(
                    "⬇️ Download QR Code",
                    data=qr_bytes,
                    file_name="encryption_key_qr.png",
                    mime="image/png",
                )

            except Exception as e:
                st.error(f"Encryption failed: {e}")


# ---------- DECRYPT TAB ----------

with tab_decrypt:
    st.subheader("Upload encrypted (.enc) file")
    dec_file = st.file_uploader(
        "Encrypted file generated by the encryption tab", key="dec_file"
    )

    key_input = st.text_input(
        "Paste AES key (Base64 from QR scan)",
        type="password",
        help="Scan the QR → copy the decoded Base64 key → paste here.",
    )

    if st.button("Decrypt File"):
        if not dec_file:
            st.error("Upload an encrypted file first.")
        elif not key_input.strip():
            st.error("Paste the AES key.")
        else:
            try:
                encrypted_bytes = dec_file.read()
                key_bytes = base64.b64decode(key_input.strip())

                decrypted_bytes = decrypt_file(encrypted_bytes, key_bytes)

                out_name = dec_file.name.replace(".enc", "")
                if out_name == dec_file.name:
                    out_name = "decrypted_" + dec_file.name

                st.success("✅ Decrypted successfully!")

                st.download_button(
                    "⬇️ Download Decrypted File",
                    data=decrypted_bytes,
                    file_name=out_name,
                    mime="application/octet-stream",
                )

            except Exception as e:
                st.error(f"Decryption failed: {e}")
